/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Images } from "./components/carousel-component/carousel-component";
import { NavigationDirection } from "./components/carousel-component/navigation-component/constants";
export namespace Components {
    interface CarouselComponent {
        "delay": number;
        "images": Array<Images>;
    }
    interface ImageComponent {
        "alt": string;
        "isActive": boolean;
        "src": string;
    }
    interface IndicatorComponent {
        "isActive": boolean;
        "slideIndex": number;
    }
    interface NavigationComponent {
        "navigationDirection": NavigationDirection;
        "text": string;
    }
}
export interface IndicatorComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIndicatorComponentElement;
}
export interface NavigationComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNavigationComponentElement;
}
declare global {
    interface HTMLCarouselComponentElement extends Components.CarouselComponent, HTMLStencilElement {
    }
    var HTMLCarouselComponentElement: {
        prototype: HTMLCarouselComponentElement;
        new (): HTMLCarouselComponentElement;
    };
    interface HTMLImageComponentElement extends Components.ImageComponent, HTMLStencilElement {
    }
    var HTMLImageComponentElement: {
        prototype: HTMLImageComponentElement;
        new (): HTMLImageComponentElement;
    };
    interface HTMLIndicatorComponentElement extends Components.IndicatorComponent, HTMLStencilElement {
    }
    var HTMLIndicatorComponentElement: {
        prototype: HTMLIndicatorComponentElement;
        new (): HTMLIndicatorComponentElement;
    };
    interface HTMLNavigationComponentElement extends Components.NavigationComponent, HTMLStencilElement {
    }
    var HTMLNavigationComponentElement: {
        prototype: HTMLNavigationComponentElement;
        new (): HTMLNavigationComponentElement;
    };
    interface HTMLElementTagNameMap {
        "carousel-component": HTMLCarouselComponentElement;
        "image-component": HTMLImageComponentElement;
        "indicator-component": HTMLIndicatorComponentElement;
        "navigation-component": HTMLNavigationComponentElement;
    }
}
declare namespace LocalJSX {
    interface CarouselComponent {
        "delay"?: number;
        "images"?: Array<Images>;
    }
    interface ImageComponent {
        "alt"?: string;
        "isActive"?: boolean;
        "src"?: string;
    }
    interface IndicatorComponent {
        "isActive"?: boolean;
        "onChangeSlide"?: (event: IndicatorComponentCustomEvent<number>) => void;
        "slideIndex"?: number;
    }
    interface NavigationComponent {
        "navigationDirection"?: NavigationDirection;
        "onClickNextOrPrevSlide"?: (event: NavigationComponentCustomEvent<NavigationDirection>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "carousel-component": CarouselComponent;
        "image-component": ImageComponent;
        "indicator-component": IndicatorComponent;
        "navigation-component": NavigationComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "carousel-component": LocalJSX.CarouselComponent & JSXBase.HTMLAttributes<HTMLCarouselComponentElement>;
            "image-component": LocalJSX.ImageComponent & JSXBase.HTMLAttributes<HTMLImageComponentElement>;
            "indicator-component": LocalJSX.IndicatorComponent & JSXBase.HTMLAttributes<HTMLIndicatorComponentElement>;
            "navigation-component": LocalJSX.NavigationComponent & JSXBase.HTMLAttributes<HTMLNavigationComponentElement>;
        }
    }
}
